package com.cyberwallet.walletapi.exception;

/**
 * Enum que representa todos los códigos de error QA-driven de CyberWallet.
 */
public enum ErrorCode {
    INVALID_TOKEN,
    ACCESS_DENIED,
    USER_BLOCKED,
    USER_UNVERIFIED,
    ACCOUNT_CLOSED,
    INVALID_AMOUNT,
    INSUFFICIENT_FUNDS,
    CANNOT_TRANSFER_TO_SELF,
    RECIPIENT_NOT_FOUND,
    RECIPIENT_ACCOUNT_BLOCKED,
    RECIPIENT_ACCOUNT_CLOSED,
    RECIPIENT_ACCOUNT_UNVERIFIED,
    PAYMENT_GATEWAY_ERROR,
    PAYMENT_DECLINED,
    DAILY_LIMIT_EXCEEDED,
    VALIDATION_ERROR,
    IDEMPOTENCY_CONFLICT,
    TRANSACTION_FAILED,
    INTERNAL_SERVER_ERROR
}
